[build]
  command = "ng build --configuration=production"
  publish = "dist/flight--app/browser" 
  functions = "netlify/functions"    

[build.environment]
  NODE_VERSION = "22.18.0"

# API proxy redirects - ADD THESE
[[redirects]]
  from = "/api/FlightBooking/*"
  to = "https://freeapi.miniprojectideas.com/api/FlightBooking/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/Airport/*"
  to = "https://freeapi.miniprojectideas.com/api/Airport/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/Customer/*"
  to = "https://freeapi.miniprojectideas.com/api/Customer/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/BookTicket/*"
  to = "https://freeapi.miniprojectideas.com/api/Customer/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Add headers for CORS
[[headers]]
  for = "/api/*"
  [headers.values]
    "Access-Control-Allow-Origin" = "*"
    "Access-Control-Allow-Methods" = "GET, POST, PUT, DELETE, OPTIONS"
    "Access-Control-Allow-Headers" = "Content-Type, Authorization"

# Disable the Angular plugin
#[plugins]
 # package = "@netlify/angular-runtime"
  #enabled = false