[build]
  command = "ng build --configuration=production"
  publish = "dist/flight--app/browser" 
  functions = "netlify/functions"    

[build.environment]
  NODE_VERSION = "22.18.0"                 # Match your local Node version

[[redirects]]
from = "/*"
to = "/index.html"
status = 200


# Disable the Angular plugin
#[plugins]
 # package = "@netlify/angular-runtime"
  #enabled = false